<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-D9B72J2S" failures="2" tests="4" name="Surefire test" time="26.041" errors="0" timestamp="2024-07-04T17:54:34 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.659">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.015">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at stepDefs.LoginStepDef.LaunchURL(LoginStepDef.java:28)
at ✽.user has launched the url "https://www.google.com/"(file:///C:/Users/91945/eclipse-workspace/CucumberRevison/src/test/resources/parallelfeatures/parallel1.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.168">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.527">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at stepDefs.LoginStepDef.LaunchURL(LoginStepDef.java:28)
at ✽.user has launched the url "https://www.google.com/"(file:///C:/Users/91945/eclipse-workspace/CucumberRevison/src/test/resources/parallelfeatures/parallel1.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Surefire test -->
